# bag
topic_lidar: /velodyne_points
topic_imu: /imu/data

LidarModel: VLP_16_SIMU
vlp16_ring_case: 0

scan4map: 15.0
ndtResolution: 0.5
ndt_key_frame_downsample: 0.1
map_downsample_size: 0.25

knot_distance: 0.02

use_gui: false

segment_num: 1
selected_segment:
  - start_time: 0
    end_time: 5
    path_bag: "/root/catkin_oa_calib/src/OA-LICalib/data/test1.bag"

plane_motion: false

gyro_weight: 2.80
accel_weight: 1.85
lidar_weight: 1.0

lock_accel_bias: false

opt_timeoffset: false
timeoffset_padding: 0.01

opt_lidar_intrinsic: false  # Отключите на первых запусках
opt_IMU_intrinsic: false    # Отключите на первых запусках

iteration_num: 5  # Уменьшите количество итераций

extrinsic:
  Trans: [0.25, 0.13, 0.07]
  Trans_prior: [0.25, 0.13, 0.07]
  Rot: [1, 0, 0, 0, 1, 0, 0, 0, 1]